### ISSUE TITLE
Plugin crashes when using telnet to test the connection

### ISSUE THREAD

**Issue by AirOnSkin** [logstash-plugins/logstash-input-relp#5]
Hello,

Somehow, the RELP plugin (and with it the whole Logstash server) crashes, when I do a connection test with telnet from a client to the Logstash server on the port the plugin listens to.

plugin configuration:
```
input {
  relp {
    port => 1425
    host => "111.22.333.103"
    type => "syslog"
    codec => "json"
  }
}
```

cli on client:
```
root@client: ~ # telnet logstash-server 1425
Trying 111.22.333.103...
Connected to logstash-server.
Escape character is '^]'.
^]
telnet> q
Connection closed.
```

output on server (running in debug mode):
```
... a lot of log output ...
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Relp host=>"111.22.333.103", type=>"syslog">
  Error: Relp::ConnectionClosed
  Exception: Relp::ConnectionClosed
  Stack: /opt/logstash/lib/logstash/util/relp.rb:79:in `frame_read'
/opt/logstash/lib/logstash/util/relp.rb:123:in `accept'
/opt/logstash/lib/logstash/inputs/relp.rb:66:in `run'
org/jruby/RubyKernel.java:1521:in `loop'
/opt/logstash/lib/logstash/inputs/relp.rb:63:in `run'
/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'
/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"168"}
/opt/logstash/lib/logstash/util/relp.rb:79:in `frame_read'
/opt/logstash/lib/logstash/util/relp.rb:123:in `accept'
/opt/logstash/lib/logstash/inputs/relp.rb:66:in `run'
org/jruby/RubyKernel.java:1521:in `loop'
/opt/logstash/lib/logstash/inputs/relp.rb:63:in `run'
/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'
/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'
Pipeline shutdown complete. {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"89"}
```

The moment I quit telnet (entering 'q' and then hitting ENTER), the plugin breaks.
The server runs fine until I quit the telnet connection.

Cheers,
Stefan

**Comment by jordansissel** [comment]
Reported by another user in IRC today.

**Comment by muellert** [comment]
I can only guess that the problem arises within lib/logstash/util/relp.rb, and that, somehow, the connection breakage leads to the plugin trying to parse a partial and thus broken message, which then gets propagated upwards, near line 96.

**Comment by offmindby** [comment]
Got same error in 1.4.2 Logstash

**Comment by nicolasguyomar** [comment]
Same error also in 1.4.2

**Comment by nicolasguyomar** [comment]
Hi, isn't that the same as https://github.com/elastic/logstash/issues/1742  ?

**Comment by nicolasguyomar** [comment]
Hi,
Thanks to https://github.com/elastic/logstash/issues/1742 the logstash relp input does not break anymore, but using telnet from a loadbalancer still generate quite a lot of warning because of the socket content being not compliant with relp protocol

I'm getting exception while reading the 'command' part because there is no command

org/jruby/RubyIO.java:2538:in `readline'
/opt/logstash-1.4.2/lib/logstash/util/relp.rb:69:in `frame_read'
/opt/logstash-1.4.2/lib/logstash/util/relp.rb:140:in `relp_setup_connection'
/opt/logstash-1.4.2/lib/logstash/inputs/relp.rb:70:in `run'


{:timestamp=>"2015-06-26T15:27:26.133000+0200", :message=>"FrameReadException", :level=>:debug, :file=>"logstash/util/relp.rb", :line=>"87"}
{:timestamp=>"2015-06-26T15:27:26.134000+0200", :message=>"Relp error: Relp::FrameReadException Relp::FrameReadException", :level=>:warn, :file=>"logstash/inputs/relp.rb", :line=>"80"}

I think this is the expected behaviour, but still, I have no solution to do a 'clean' connection test using telnet
